spring:
  datasource:
    url: jdbc:postgresql://delivva-core.c4cvypbefffg.eu-north-1.rds.amazonaws.com:5432/postgres
    username: delivva
    password: password
  rabbitmq:
    username: Delivva
    password: delivvadevelopers4
    addresses: amqps://b-24e330b5-34c3-48c1-87df-d65aefcd7ec3.mq.us-east-1.amazonaws.com:5671

cloud:
  map:
    url: https://nominatim.openstreetmap.org/reverse
  auth-service:
    url: http://Delivva-testing-environment-env.eba-jighrhr6.us-east-1.elasticbeanstalk.com
  dispute-service:
    url: http://localhost:8081 # will be changed once dispute service is deployed

jwt:
  secret-key: 753778214125442A472IkphdZSIsImasV4cCIee6MTY4sdNzUwMTQwN3F452848567890iuyiu67567886578uyutuio78654678976549eyJS678965467uior678545
