server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/delivva_core
    username: delivva
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-changelog.yaml
