server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://delivva-core.c4cvypbefffg.eu-north-1.rds.amazonaws.com:5432/postgres
    username: delivva
    password: password
  rabbitmq:
    username: Delivva
    password: delivvadevelopers4
    addresses: amqps://b-24e330b5-34c3-48c1-87df-d65aefcd7ec3.mq.us-east-1.amazonaws.com:5671
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-changelog.yaml

rabbitmq:
  exchange:
    name: geo_direct_exchange
  routing:
    key:
      geo: geo_service_routing_key

cloud:
  map:
    url: https://nominatim.openstreetmap.org/reverse
  auth-service:
    url: http://Delivva-testing-environment-env.eba-jighrhr6.us-east-1.elasticbeanstalk.com
  dispute-service:
    url: http://Delivva-dispute-env.eba-chhhwrqq.eu-north-1.elasticbeanstalk.com
  geo-service:
    url: http://ec2-51-20-56-164.eu-north-1.compute.amazonaws.com:5000
jwt:
  secret-key: 753778214125442A472IkphdZSIsImasV4cCIee6MTY4sdNzUwMTQwN3F452848567890iuyiu67567886578uyutuio78654678976549eyJS678965467uior678545

maps:
  api:
    key: AIzaSyBgcWJIB1LLR5BmWIDxyCxsG6wdoaIefZY
    url: https://maps.googleapis.com/maps/api/geocode/json?latlng=