spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivva_core
    username: postgres
    password: 6040
  rabbitmq:
    username: Delivva
    password: delivvadevelopers4
    addresses: amqps://b-24e330b5-34c3-48c1-87df-d65aefcd7ec3.mq.us-east-1.amazonaws.com:5671

cloud:
  map:
    url: https://nominatim.openstreetmap.org/reverse
  auth-service:
    url: http://Delivva-testing-environment-env.eba-jighrhr6.us-east-1.elasticbeanstalk.com
  dispute-service:
    url: http://localhost:8081